### ISSUE TITLE
font change

### ISSUE THREAD

**Issue by taffarelemilio** [avrcoelho/react-credit-card-with-flip#1]
The component changes my font family with

`* {
    margin: 0px;
    padding: 0px;
    box-sizing: border-box;
    outline: 0px;
    font-family: "Bitstream Vera Sans Mono", Consolas, Courier, monospace;
    text-rendering: optimizelegibility !important;
    -webkit-font-smoothing: antialiased !important;
}`

<style data-styled="active" data-styled-version="5.1.0"></style>

**Comment by avrcoelho** [comment]
fixed
